services:
  - type: web
    name: streamo-web
    runtime: docker
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RENDER_KAFKA_HOST
        sync: false
      - key: RENDER_KAFKA_PORT
        sync: false
      - key: PORT
        value: 10000


