apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: streamo_user
    database: streamo
    secureJsonData:
      password: streamo_password
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500
    isDefault: true
